//! M5 — Markdown projection of a Surface project (boundary checklist
//! per spec §6.4.3).

use std::collections::BTreeMap;
use std::fmt::Write;
use std::fs;
use std::path::Path;

use anyhow::{Context, Result};
use surfacide_ast::compose::ComposeBlock;
use surfacide_ast::decl::{ActorDecl, EventDecl, ObservableDecl, TypeAliasDecl};
use surfacide_ast::slot::{
    AuthChannelTag, AvailabilityValue, FreshnessValue, IdempotencyValue, ObservabilityValue,
    PiiClass, RateLimitValue, RetentionValue, SlotKind, SlotProvenance, SlotValue,
};
use surfacide_ast::surface::{ActionDecl, SurfaceBlock};
use surfacide_ast::{Decl, Project};
use surfacide_check::slots::elaborate;

/// Emit per-module Markdown files into `out_dir`. Returns the list of
/// files written.
pub fn emit(project: &Project, out_dir: &Path) -> Result<Vec<std::path::PathBuf>> {
    fs::create_dir_all(out_dir).with_context(|| format!("creating {}", out_dir.display()))?;
    let mut written = Vec::new();
    for (key, module) in &project.modules {
        let filename = format!("{}.md", sanitize_filename(key));
        let path = out_dir.join(&filename);
        let body = render_module(module);
        fs::write(&path, body).with_context(|| format!("writing {}", path.display()))?;
        written.push(path);
    }
    Ok(written)
}

fn sanitize_filename(name: &str) -> String {
    name.replace('.', "-").replace('/', "-")
}

/// Render a single `ModuleAggregate` as a Markdown string.
pub fn render_module(module: &surfacide_ast::project::ModuleAggregate) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# {} — generated documentation", module.name);
    out.push('\n');
    let _ = writeln!(
        out,
        "> *Auto-generated by `surfacide emit docs`. Do not edit; regenerate from the `.surf` source.*"
    );
    out.push('\n');
    out.push_str("---\n\n");
    let _ = writeln!(out, "## Module: `{}`", module.name);
    out.push('\n');

    let mut surface_blocks: Vec<&SurfaceBlock> = Vec::new();
    let mut actors: Vec<&ActorDecl> = Vec::new();
    let mut events: Vec<&EventDecl> = Vec::new();
    let mut types: Vec<&TypeAliasDecl> = Vec::new();
    let mut top_observables: Vec<&ObservableDecl> = Vec::new();
    let mut composes: Vec<&ComposeBlock> = Vec::new();

    for decl in &module.decls {
        match decl {
            Decl::Surface(s) => surface_blocks.push(s),
            Decl::Actor(a) => actors.push(a),
            Decl::Event(e) => events.push(e),
            Decl::TypeAlias(t) => types.push(t),
            Decl::Observable(o) => top_observables.push(o),
            Decl::Compose(c) => composes.push(c),
            _ => {}
        }
    }

    if let Some(d) = surface_blocks.first().and_then(|s| s.doc.as_deref()) {
        out.push_str(d.trim());
        out.push_str("\n\n> *Source: `surface { … }` doc-string.*\n\n---\n\n");
    }

    if !actors.is_empty() {
        out.push_str("## Actors\n\n");
        for a in &actors {
            match (&a.extends, &a.doc) {
                (Some(parent), Some(doc)) => {
                    let _ = writeln!(out, "- **{}** *(extends `{}`)* — {}", a.name, parent, single_line(doc));
                }
                (Some(parent), None) => {
                    let _ = writeln!(out, "- **{}** *(extends `{}`)*", a.name, parent);
                }
                (None, Some(doc)) => {
                    let _ = writeln!(out, "- **{}** — {}", a.name, single_line(doc));
                }
                (None, None) => {
                    let _ = writeln!(out, "- **{}**", a.name);
                }
            }
        }
        out.push_str("\n---\n\n");
    }

    if !types.is_empty() {
        out.push_str("## Vocabulary\n\n");
        for t in &types {
            let doc = t.doc.as_deref().unwrap_or("");
            let _ = writeln!(out, "- **{}** — type alias.{}",
                t.name,
                if doc.is_empty() { String::new() } else { format!(" {}", single_line(doc)) }
            );
        }
        out.push_str("\n---\n\n");
    }

    if let Some(s) = surface_blocks.first() {
        emit_per_actor_sections(s, &actors, &top_observables, &mut out);
    }

    if !events.is_empty() {
        out.push_str("## Events catalogue\n\n");
        out.push_str("| Event | Fields |\n|---|---|\n");
        for e in &events {
            let fields = e
                .fields
                .iter()
                .map(|f| format!("`{}: <type>`", f.name.name))
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(out, "| `{}` | {} |", e.name, if fields.is_empty() { "—".to_string() } else { fields });
        }
        out.push('\n');
    }

    if !composes.is_empty() {
        out.push_str("---\n\n## Compose blocks\n\n");
        for c in &composes {
            let _ = writeln!(out, "### `{}`\n", c.name);
            let _ = writeln!(out, "Members: {}\n", format_idents(&c.members));
            if !c.channels.is_empty() {
                out.push_str("Channels:\n\n");
                for ch in &c.channels {
                    let _ = writeln!(out, "- `{}` — from `{}` to `{}`", ch.name, ch.from_comp, ch.to_comp);
                }
                out.push('\n');
            }
            if let Some(ack) = &c.acknowledged {
                out.push_str("Acknowledged obligations:\n\n");
                for entry in &ack.entries {
                    let _ = writeln!(out, "- `{}`", entry.kind.name());
                    if let Some(b) = &entry.because {
                        let _ = writeln!(out, "  - because: *{}*", b);
                    }
                }
                out.push('\n');
            }
        }
    }

    out
}

fn single_line(s: &str) -> String {
    s.split('\n').next().unwrap_or(s).trim().to_string()
}

fn format_idents(ids: &[surfacide_ast::Ident]) -> String {
    if ids.is_empty() {
        "—".to_string()
    } else {
        ids.iter().map(|i| format!("`{}`", i.name)).collect::<Vec<_>>().join(", ")
    }
}

fn emit_per_actor_sections(
    surface: &SurfaceBlock,
    actors: &[&ActorDecl],
    top_observables: &[&ObservableDecl],
    out: &mut String,
) {
    let mut actions_by_actor: BTreeMap<String, Vec<&ActionDecl>> = BTreeMap::new();
    for a in &surface.actions {
        actions_by_actor.entry(a.actor.actor_ty.name.clone()).or_default().push(a);
    }

    let mut observables_by_actor: BTreeMap<String, Vec<&ObservableDecl>> = BTreeMap::new();
    for o in &surface.observables {
        let key = o.for_actor.as_ref().map(|b| b.actor_ty.name.clone()).unwrap_or_else(|| "Global".to_string());
        observables_by_actor.entry(key).or_default().push(o);
    }
    for o in top_observables {
        let key = o.for_actor.as_ref().map(|b| b.actor_ty.name.clone()).unwrap_or_else(|| "Global".to_string());
        observables_by_actor.entry(key).or_default().push(o);
    }

    for actor in actors {
        let key = actor.name.name.clone();
        let _ = writeln!(out, "# {}\n", key);
        let observs = observables_by_actor.remove(&key).unwrap_or_default();
        if !observs.is_empty() {
            let _ = writeln!(out, "## What a {} can observe\n", key);
            out.push_str("| Observable | Meaning |\n|---|---|\n");
            for o in &observs {
                let doc = o.doc.as_deref().unwrap_or("—");
                let _ = writeln!(out, "| `{}(...)` | {} |", o.name, single_line(doc));
            }
            out.push('\n');
        }
        let actions = actions_by_actor.remove(&key).unwrap_or_default();
        if !actions.is_empty() {
            let _ = writeln!(out, "## What a {} can do\n", key);
            for a in &actions {
                render_action(a, surface, out);
            }
        }
    }

    let mut leftover_observs: Vec<&ObservableDecl> = Vec::new();
    for (_a, mut v) in std::mem::take(&mut observables_by_actor) {
        leftover_observs.append(&mut v);
    }
    if !surface.internal_actions.is_empty() || !leftover_observs.is_empty() {
        out.push_str("# System (internal)\n\n");
        if !leftover_observs.is_empty() {
            out.push_str("## Global observables\n\n");
            out.push_str("| Observable | Meaning |\n|---|---|\n");
            for o in &leftover_observs {
                let doc = o.doc.as_deref().unwrap_or("—");
                let _ = writeln!(out, "| `{}(...)` | {} |", o.name, single_line(doc));
            }
            out.push('\n');
        }
        if !surface.internal_actions.is_empty() {
            out.push_str("## Internal actions\n\n");
            for ia in &surface.internal_actions {
                render_action(&ia.action, surface, out);
            }
        }
    }
}

fn render_action(action: &ActionDecl, surface: &SurfaceBlock, out: &mut String) {
    let _ = writeln!(
        out,
        "### `{}({})` — {}",
        action.name,
        action.params.iter().map(|p| p.name.name.as_str()).collect::<Vec<_>>().join(", "),
        action.doc.as_deref().map(single_line).unwrap_or_else(|| "action".to_string())
    );
    out.push('\n');
    if let Some(doc) = &action.doc {
        out.push_str(doc.trim());
        out.push_str("\n\n");
    }
    if action.is_internal {
        out.push_str(
            "> *Internal action (control plane / housekeeping). Per §6.4.6, `internal_action` auto-fills `auth_channel: trusted_caller`, `rate_limit: waived: \"internal\"`, `availability: maintenance_window` (overridable).*\n\n",
        );
    }
    if !action.raises.is_empty() {
        out.push_str("**Errors:**\n\n");
        out.push_str("| Error name |\n|---|\n");
        for r in &action.raises {
            let _ = writeln!(out, "| `{}` |", r.name);
        }
        out.push('\n');
    }
    let (elab, _diags) = elaborate(action, surface.defaults.as_ref());
    out.push_str("**Boundary checklist** *(from §6.4 mandatory slots, v0.10.1)*\n\n");
    out.push_str("| Slot | Value | Provenance |\n|---|---|---|\n");
    for kind in SlotKind::canonical_order() {
        if let Some(slot) = elab.get(kind) {
            let _ = writeln!(out, "| {} | {} | {} |", kind.name(), render_slot_value(&slot.value), render_provenance(slot.provenance));
        } else {
            let _ = writeln!(out, "| {} | **MISSING** | — |", kind.name());
        }
    }
    out.push('\n');
    out.push_str("---\n\n");
}

fn render_provenance(p: SlotProvenance) -> &'static str {
    match p {
        SlotProvenance::Explicit => "explicit",
        SlotProvenance::Default => "default",
        SlotProvenance::InternalActionPreset => "internal-preset",
    }
}

fn render_slot_value(v: &SlotValue) -> String {
    match v {
        SlotValue::Idempotency(i) => match i {
            IdempotencyValue::Idempotent => "idempotent".into(),
            IdempotencyValue::IdempotentBy(args) => format!(
                "idempotent by({})",
                args.iter().map(|i| i.name.as_str()).collect::<Vec<_>>().join(", ")
            ),
            IdempotencyValue::AtMostOnce => "at_most_once".into(),
            IdempotencyValue::AtLeastOnce => "at_least_once".into(),
        },
        SlotValue::AuthChannel(ac) => {
            let names: Vec<&str> = ac.channels.iter().map(|c| auth_channel_name(*c)).collect();
            if ac.channels.len() <= 1 && !ac.set_form {
                names.first().copied().unwrap_or("?").to_string()
            } else {
                format!("{{ {} }}", names.join(", "))
            }
        }
        SlotValue::Retention(r) => match r {
            RetentionValue::Ephemeral => "ephemeral".into(),
            RetentionValue::Transactional => "transactional".into(),
            RetentionValue::Audit { period } => format!("audit(period={})", period.name),
            RetentionValue::Pii { class, ttl } => format!("pii(class={}, ttl={})", pii_class_name(*class), ttl.name),
            RetentionValue::Secret => "secret".into(),
        },
        SlotValue::RateLimit(rl) => match rl {
            RateLimitValue::PerActor { n, period } => format!("per_actor({}, per={})", n, period.name),
            RateLimitValue::PerTarget { arg, n, period } => format!("per_target({}, {}, per={})", arg.name, n, period.name),
            RateLimitValue::Global { n, period } => format!("global({}, per={})", n, period.name),
            RateLimitValue::Unlimited => "unlimited".into(),
        },
        SlotValue::Observability(o) => match o {
            ObservabilityValue::CallerOnly(events) => format!("caller_only({})", events.iter().map(|e| e.name.as_str()).collect::<Vec<_>>().join(", ")),
            ObservabilityValue::Target { arg, events } => format!("target({}, {})", arg.name, events.iter().map(|e| e.name.as_str()).collect::<Vec<_>>().join(", ")),
            ObservabilityValue::Broadcast(events) => format!("broadcast({})", events.iter().map(|e| e.name.as_str()).collect::<Vec<_>>().join(", ")),
            ObservabilityValue::Silent => "silent".into(),
        },
        SlotValue::Availability(a) => match a {
            AvailabilityValue::Critical => "critical".into(),
            AvailabilityValue::BestEffort => "best_effort".into(),
            AvailabilityValue::MaintenanceWindow => "maintenance_window".into(),
            AvailabilityValue::ReadOnlyFailover => "read_only_failover".into(),
        },
        SlotValue::Freshness(f) => match f {
            FreshnessValue::Strong => "strong".into(),
            FreshnessValue::Bounded { epoch, n } => format!("bounded({}, n={})", epoch.name, n),
            FreshnessValue::Eventual { epoch } => epoch.as_ref().map(|e| format!("eventual({})", e.name)).unwrap_or_else(|| "eventual".into()),
            FreshnessValue::StaleWhileRevalidate { epoch, n } => format!("stale_while_revalidate({}, n={})", epoch.name, n),
            FreshnessValue::NotApplicable => "not_applicable".into(),
        },
        SlotValue::Waived { reason, .. } => format!("waived: \"{}\"", reason),
        SlotValue::Unknown(id) => format!("**unknown:** `{}`", id.name),
    }
}

fn auth_channel_name(t: AuthChannelTag) -> &'static str { t.name() }
fn pii_class_name(c: PiiClass) -> &'static str { c.name() }

#[cfg(test)]
mod tests {
    use super::*;
    use surfacide_ast::*;
    use surfacide_ast::project::ModuleAggregate;
    use surfacide_ast::surface::*;
    use surfacide_ast::decl::*;

    fn id(s: &str) -> Ident { Ident::new(s, Span::synthetic()) }

    fn mk_module(name: &str, decls: Vec<Decl>) -> ModuleAggregate {
        ModuleAggregate { name: QualifiedName::new(vec![id(name)]), private: false, files: Vec::new(), decls }
    }

    fn mk_actor(name: &str, doc: &str) -> ActorDecl {
        ActorDecl { name: id(name), extends: None, doc: Some(doc.into()), span: Span::synthetic() }
    }

    fn mk_surface_with_action(actor_ty: &str, action_name: &str) -> SurfaceBlock {
        SurfaceBlock {
            state: Vec::new(),
            init: Vec::new(),
            fairness: Vec::new(),
            properties: Vec::new(),
            defaults: None,
            actions: vec![ActionDecl {
                name: id(action_name),
                params: Vec::new(),
                return_ty: None,
                actor: ActorBinder { name: id("u"), actor_ty: id(actor_ty), span: Span::synthetic() },
                when_pre: None,
                raises: Vec::new(),
                slots: Vec::new(),
                body: EffectBlock { stmts: Vec::new(), span: Span::synthetic() },
                doc: Some("does a thing".into()),
                span: Span::synthetic(),
                is_internal: false,
            }],
            internal_actions: Vec::new(),
            observables: Vec::new(),
            span: Span::synthetic(),
            doc: Some("Module doc".into()),
        }
    }

    #[test]
    fn empty_module_renders_header_only() {
        let m = mk_module("M", Vec::new());
        let s = render_module(&m);
        assert!(s.contains("# M — generated documentation"));
        assert!(s.contains("## Module: `M`"));
    }

    #[test]
    fn action_renders_with_boundary_checklist_showing_missing() {
        let mut decls = vec![Decl::Actor(mk_actor("User", "the user"))];
        decls.push(Decl::Surface(mk_surface_with_action("User", "transfer")));
        let m = mk_module("Banking", decls);
        let s = render_module(&m);
        assert!(s.contains("### `transfer()` — does a thing"));
        assert!(s.contains("**Boundary checklist**"));
        let missing_count = s.matches("MISSING").count();
        assert_eq!(missing_count, 7, "expected 7 MISSING, got {}", missing_count);
    }

    #[test]
    fn actors_section_lists_each_actor() {
        let m = mk_module("M", vec![
            Decl::Actor(mk_actor("Alice", "first")),
            Decl::Actor(mk_actor("Bob", "second")),
        ]);
        let s = render_module(&m);
        assert!(s.contains("## Actors"));
        assert!(s.contains("**Alice**"));
        assert!(s.contains("**Bob**"));
    }

    #[test]
    fn sanitize_filename_replaces_dots() {
        assert_eq!(sanitize_filename("Banking.Ledger"), "Banking-Ledger");
        assert_eq!(sanitize_filename("M"), "M");
    }

    #[test]
    fn emit_writes_one_file_per_module() {
        let dir = std::env::temp_dir().join("surfacide-docs-test");
        let _ = std::fs::remove_dir_all(&dir);
        let mut project = Project::new();
        project.modules.insert(
            "M".to_string(),
            mk_module("M", vec![Decl::Actor(mk_actor("U", "user"))]),
        );
        let written = super::emit(&project, &dir).unwrap();
        assert_eq!(written.len(), 1);
        let body = std::fs::read_to_string(&written[0]).unwrap();
        assert!(body.contains("**U**"));
    }
}
